= Example 01

image:https://img.shields.io/badge/donations-Patreon-f96854.svg[link="https://www.patreon.com/user?u=6609318"]

Simple JavaFX based application that can issue a REST call to GitHub's API.
Relies on JDeferred to invoke network calls on a background thread.

The code is explained in full detail at https://community.oracle.com/docs/DOC-1005785
and https://community.oracle.com/docs/DOC-1007145.

Libraries used in this project:

 * link:https://github.com/google/guice[Google Guice].
 * link:https://github.com/xvik/guice-ext-annotations[guice-ext-annotations].
 * link:http://square.github.io/retrofit[Retrofit]
 * link:https://github.com/FasterXML/jackson[Jackson].
 * link:https://projectlombok.org/features/index.html[Lombok].
 * link:http://jdeferred.org/[JDeferred].
 * link:https://github.com/bennidi/mbassador[MBassador].
 * link:https://github.com/google/guava[Google Guava].

== Running

Run the application by invoking

    $ ./gradlew run

== IDE Configuration

Make sure to have annotation processing enabled in your IDE.

[horizontal]
NetBeans:: This setting is enabled by default. JARs with annotation processors
will be automatically found in the classpath.
IntelliJ:: You must enable "Annotation Processing" in the project preferences.
JARs with annotation processors will be found in the classpath.
Eclipse:: You must enable "Annotation Processing" in the project preferences.
You also need to manually specify which JARs contain annotation processors,
this would be the Lombok dependency. Alternatively there's an UI based installer
for Lombok that solves this problem.

== License

All code found in this repository is licensed under GPL v3

[source]
----
Copyright 2016-2017 Andres Almiray

This file is part of Java Trove Examples

Java Trove Examples is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Java Trove Examples is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Java Trove Examples. If not, see <http://www.gnu.org/licenses/>.
----
