= Chat 01

image:https://img.shields.io/badge/donations-Patreon-f96854.svg[link="https://www.patreon.com/user?u=6609318"]

Simple JavaFX based chat application. Kryo and Kryonet are used as encoding
and transport.

Libraries used in this project:

 * link:https://github.com/google/guice[Google Guice].
 * link:https://github.com/xvik/guice-ext-annotations[guice-ext-annotations].
 * link:https://github.com/EsotericSoftware/kryo[Kryo]
 * link:https://github.com/EsotericSoftware/kryonet[Kryonet]
 * link:https://projectlombok.org/features/index.html[Lombok].
 * link:http://jdeferred.org/[JDeferred].
 * link:https://github.com/bennidi/mbassador[MBassador].

== Running

Run the server by invoking

    $ ./gradlew :server:run

Run the client by invoking

    $ ./gradlew :client:run

== IDE Configuration

Make sure to have annotation processing enabled in your IDE.

[horizontal]
NetBeans:: This setting is enabled by default. JARs with annotation processors
will be automatically found in the classpath.
IntelliJ:: You must enable "Annotation Processing" in the project preferences.
JARs with annotation processors will be found in the classpath.
Eclipse:: You must enable "Annotation Processing" in the project preferences.
You also need to manually specify which JARs contain annotation processors,
this would be the Lombok dependency. Alternatively there's an UI based installer
for Lombok that solves this problem.

== License

All code found in this repository is licensed under GPL v3

[source]
----
Copyright 2016-2020 Andres Almiray

This file is part of Java Trove Examples

Java Trove Examples is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Java Trove Examples is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Java Trove Examples. If not, see <http://www.gnu.org/licenses/>.
----
